(in-package :clipmunk.accessors)

(defmacro make-accessors (c-struct)
  `(progn
     ,@(loop for slot-name in (foreign-slot-names c-struct)
	  for accessor-name = (intern (concatenate 'string (symbol-name c-struct)
						   "-"
						   (symbol-name slot-name)))
	  append (list `(defmacro ,accessor-name (ptr)
			  (list 'foreign-slot-value ptr '',c-struct '',slot-name))
		       `(export ',accessor-name)))))

(make-accessors clipmunk.bindings:vect)
(make-accessors clipmunk.bindings:bb)
(make-accessors clipmunk.bindings:array)
(make-accessors clipmunk.bindings:hash-set-bin)
(make-accessors clipmunk.bindings:hash-set)
(make-accessors clipmunk.bindings:handle)
(make-accessors clipmunk.bindings:space-hash-bin)
(make-accessors clipmunk.bindings:space-hash)
(make-accessors clipmunk.bindings:component-node)
(make-accessors clipmunk.bindings:body)
(make-accessors clipmunk.bindings:segment-query-info)
(make-accessors clipmunk.bindings:shape-class)
(make-accessors clipmunk.bindings:shape)
(make-accessors clipmunk.bindings:circle-shape)
(make-accessors clipmunk.bindings:segment-shape)
(make-accessors clipmunk.bindings:poly-shape-axis)
(make-accessors clipmunk.bindings:poly-shape)
(make-accessors clipmunk.bindings:contact)
(make-accessors clipmunk.bindings:arbiter)
(make-accessors clipmunk.bindings:constraint-class)
(make-accessors clipmunk.bindings:constraint)
(make-accessors clipmunk.bindings:collision-handler)
(make-accessors clipmunk.bindings:contact-buffer-header)
(make-accessors clipmunk.bindings:space)
